language: c

addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target check
